FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app
EXPOSE 8007

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore SampleWebApiDemo.csproj

# copy everything else and build app
COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1.2-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "SampleWebApiDemo.dll"]