##################################################################################################
# simpleapi Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
 name: simpleapi
 namespace: simpleapi-hc-ns
 labels:
   app: simpleapi
   version: v1
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort: 80
   nodePort: 30006
   name: http
 selector:
   app: simpleapi
   version: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: simpleapi
 namespace: simpleapi-hc-ns
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: simpleapi
       version: v1
   spec:
     containers:
     - name: simpleapi
       image: harshalschaudhari/sampleapi
       imagePullPolicy: Always
       ports:
       - containerPort: 80
       volumeMounts:
       - name: app-config
         mountPath: /app/configoverride
         readOnly: true
     volumes:
     - name: app-config
       configMap:
         name: aicv2-serviceconfigs
         items:
         - key: simpleapi.json
           path: simpleapi.json